### ISSUE TITLE
Migration to .Net5.0

### ISSUE THREAD

**Issue by Ghislain1** [TheMostDifficultStep/Mjolnir#2]
When do you plan to migrate to new .Net Framework?

**Comment by TheMostDifficultStep** [comment]
Yes! Had a problem the last time I tried. But reading around it was
supposedly a bug in Visual Studio with regard to projects that use Windows
Forms. I plan to try again.

Thanks for your interest!

**Comment by TheMostDifficultStep** [comment]
I'm on 6 and probably need to look at upgrading to dot net 7! >_<;;
